@startuml
'https://plantuml.com/class-diagram

class TrainDispatch{
List<Train> activeTrains

void DisplayTrains()
}

class Train{
 string trainCode
 List<Passanger> passangers
 List<Station> toStations
}

enum Passangertatus{
    IDLE
    BOOKED
    ONBOARD
}

class Passanger{
int passangerId
string passangerName
Train bookTrain
Passangertatus myStatus
List<Ticket> myTickets

bool bookTicket(Ticket)

}

class Station{
    string stationName
    datetime arrivalTime
}

TrainDispatch *-- Train
TrainDispatch *-- Passanger
TrainDispatch *-- Station

class Ticket{
    Train ticketTrain
'    string ticketType
'    int ticketPrice
    bool isOcupied
    Passanger bookPassanger
    Station fromStation
    Station toStation
}
Ticket *-- Train
Ticket *-- Station
Ticket *.. Passanger

TrainDispatch *-- Ticket

@enduml
