@startuml
'https://plantuml.com/sequence-diagram

autonumber

TrainDispatch -> debugApp: display_update_systime
TrainDispatch -> Train: updateTrainStatus(app.SysTime)
TrainDispatch -> debugApp: updateTrainUI
@enduml
